import type { GlobalThemeOverrides } from 'naive-ui'

/*
 * Supabase dark - naive-ui theme overrides
 * Maps docs/styles/variables.css tokens onto naive-ui component variables.
 */
export const supabaseThemeOverrides: GlobalThemeOverrides = {
  common: {
    fontFamily: "Inter, Manrope, ui-sans-serif, system-ui, sans-serif",
    fontFamilyMono: "JetBrains Mono, Source Code Pro, ui-monospace, monospace",
    textColor1: "#fafafa",
    textColor2: "#b4b4b4",
    textColor3: "#898989",
    textColorDisabled: "#4d4d4d",
    iconColor: "#b4b4b4",
    iconColorDisabled: "#4d4d4d",
    bodyColor: "#121212",
    cardColor: "#121212",
    modalColor: "#121212",
    popoverColor: "#242424",
    tableColor: "#121212",
    tableHeaderColor: "#121212",
    inputColor: "#121212",
    inputColorDisabled: "#1a1a1a",
    actionColor: "#242424",
    tableColorHover: "#1a1a1a",
    borderColor: "#2e2e2e",
    dividerColor: "#2e2e2e",
    closeColorHover: "#b4b4b4",
    clearColor: "#393939",
    placeholderColor: "#898989",
    placeholderColorDisabled: "#4d4d4d",
    fontWeightStrong: "500",
    borderRadius: "8px",
    borderRadiusSmall: "8px",
    heightSmall: "32px",
    heightMedium: "36px",
    heightLarge: "40px",
    heightHuge: "44px",
    primaryColor: "#3ecf8e",
    primaryColorHover: "#3ecf8e",
    primaryColorPressed: "#1f4b37",
    primaryColorSuppl: "#3ecf8e",
    infoColor: "#3ecf8e",
    successColor: "#3ecf8e",
    warningColor: "#e7c100",
    errorColor: "#d03050",
  },
  Button: {
    borderRadiusMedium: "9999px",
    borderRadiusSmall: "9999px",
    borderRadiusLarge: "9999px",
    fontWeight: "500",
    textColor: "#fafafa",
    textColorHover: "#fafafa",
    textColorPressed: "#fafafa",
    textColorFocus: "#fafafa",
    textColorDisabled: "#4d4d4d",
    colorPrimary: "#3ecf8e",
    colorHoverPrimary: "#3ecf8e",
    colorPressedPrimary: "#1f4b37",
    colorFocusPrimary: "#3ecf8e",
    borderPrimary: "1px solid #3ecf8e",
    borderHoverPrimary: "1px solid #1f4b37",
    borderPressedPrimary: "1px solid #1f4b37",
    borderFocusPrimary: "1px solid #3ecf8e",
    colorInfo: "#3ecf8e",
    borderInfo: "1px solid #3ecf8e",
    colorHoverInfo: "#3ecf8e",
    borderRadius: "9999px",
  },
  Card: {
    borderRadius: "16px",
    color: "#121212",
    colorEmbedded: "#0d0d0d",
    borderColor: "#2e2e2e",
    titleTextColor: "#fafafa",
    titleFontWeight: "500",
    paddingMedium: "20px 24px",
  },
  Input: {
    borderRadius: "8px",
    color: "#121212",
    colorFocus: "#121212",
    border: "1px solid #393939",
    borderHover: "1px solid #4d4d4d",
    borderFocus: "1px solid #3ecf8e",
    boxShadowFocus: "0 0 0 0 transparent",
    placeholderColor: "#898989",
    textColor: "#fafafa",
  },
  Menu: {
    borderRadius: "8px",
    color: "transparent",
    itemColorHover: "#1a1a1a",
    itemColorActiveHover: "#0d0d0d",
    itemTextColor: "#b4b4b4",
    itemTextColorHover: "#fafafa",
    itemTextColorActive: "#3ecf8e",
    itemTextColorActiveHover: "#3ecf8e",
    itemIconColor: "#b4b4b4",
    itemIconColorHover: "#fafafa",
    itemIconColorActive: "#3ecf8e",
    itemIconColorActiveHover: "#3ecf8e",
    itemHeight: "36px",
    fontWeightActive: "500",
  },
  Tag: {
    borderRadius: "9999px",
    color: "#242424",
    border: "1px solid #2e2e2e",
    textColor: "#b4b4b4",
  },
  Layout: {
    color: "#121212",
    siderColor: "#121212",
    siderBorderColor: "#2e2e2e",
    headerColor: "#121212",
    headerBorderColor: "#2e2e2e",
  },
  Empty: {
    textColor: "#898989",
    iconColor: "#393939",
  },
  Spin: {
    color: "#3ecf8e",
  },
  Scrollbar: {
    color: "#4d4d4d",
    colorHover: "#393939",
  },
  Select: {
    peers: {
      InternalSelection: {
        borderRadius: "8px",
        color: "#121212",
        border: "1px solid #393939",
        borderHover: "1px solid #4d4d4d",
        borderFocus: "1px solid #3ecf8e",
        textColor: "#fafafa",
        placeholderColor: "#898989",
      },
    },
  },
  DataTable: {
    thColor: "#121212",
    tdColor: "#121212",
    borderColor: "#2e2e2e",
    thTextColor: "#b4b4b4",
    tdTextColor: "#fafafa",
  },
}
