import type { GlobalThemeOverrides } from "naive-ui"

/*
 * Naive UI 组件级 token 双主题覆盖：根据 isDark 切换文字/容器/边框色，
 * primary 与 phosphor-green 保持一致（品牌色不随主题变）。
 *
 * CSS 变量层面的主题切换见 tailwind.css 的 :root[data-theme='light']，
 * 本文件负责 Naive UI 组件内部色（NCard / NInput / NMenu 等）。
 */
export function buildThemeOverrides(isDark: boolean): GlobalThemeOverrides {
  const c = isDark
    ? {
        textColor1: "#fafafa",
        textColor2: "#b4b4b4",
        textColor3: "#898989",
        disabled: "#4d4d4d",
        icon: "#b4b4b4",
        iconDisabled: "#4d4d4d",
        body: "#121212",
        card: "#121212",
        modal: "#121212",
        popover: "#242424",
        table: "#121212",
        tableHeader: "#121212",
        input: "#121212",
        inputDisabled: "#1a1a1a",
        action: "#242424",
        tableHover: "#1a1a1a",
        border: "#2e2e2e",
        divider: "#2e2e2e",
        closeHover: "#b4b4b4",
        clear: "#393939",
        placeholder: "#898989",
        placeholderDisabled: "#4d4d4d",
        embed: "#0d0d0d",
        hover: "#4d4d4d",
        menuActive: "#0d0d0d",
        scrollbar: "#4d4d4d",
        scrollbarHover: "#393939",
      }
    : {
        textColor1: "#121212",
        textColor2: "#4a4a4a",
        textColor3: "#6a6a6a",
        disabled: "#c4c4c4",
        icon: "#4a4a4a",
        iconDisabled: "#c4c4c4",
        body: "#fafafa",
        card: "#ffffff",
        modal: "#ffffff",
        popover: "#ffffff",
        table: "#ffffff",
        tableHeader: "#f5f5f5",
        input: "#ffffff",
        inputDisabled: "#f0f0f0",
        action: "#f5f5f5",
        tableHover: "#f0f0f0",
        border: "#e5e5e5",
        divider: "#e5e5e5",
        closeHover: "#121212",
        clear: "#c4c4c4",
        placeholder: "#898989",
        placeholderDisabled: "#c4c4c4",
        embed: "#f0f0f0",
        hover: "#d4d4d4",
        menuActive: "#e5e5e5",
        scrollbar: "#d4d4d4",
        scrollbarHover: "#b4b4b4",
      }

  return {
    common: {
      fontFamily: "Inter, Manrope, ui-sans-serif, system-ui, sans-serif",
      fontFamilyMono: "JetBrains Mono, Source Code Pro, ui-monospace, monospace",
      textColor1: c.textColor1,
      textColor2: c.textColor2,
      textColor3: c.textColor3,
      textColorDisabled: c.disabled,
      iconColor: c.icon,
      iconColorDisabled: c.iconDisabled,
      bodyColor: c.body,
      cardColor: c.card,
      modalColor: c.modal,
      popoverColor: c.popover,
      tableColor: c.table,
      tableHeaderColor: c.tableHeader,
      inputColor: c.input,
      inputColorDisabled: c.inputDisabled,
      actionColor: c.action,
      tableColorHover: c.tableHover,
      borderColor: c.border,
      dividerColor: c.divider,
      closeColorHover: c.closeHover,
      clearColor: c.clear,
      placeholderColor: c.placeholder,
      placeholderColorDisabled: c.placeholderDisabled,
      fontWeightStrong: "500",
      borderRadius: "8px",
      borderRadiusSmall: "8px",
      heightSmall: "32px",
      heightMedium: "36px",
      heightLarge: "40px",
      heightHuge: "44px",
      primaryColor: "#3ecf8e",
      primaryColorHover: "#3ecf8e",
      primaryColorPressed: "#1f4b37",
      primaryColorSuppl: "#3ecf8e",
      infoColor: "#3ecf8e",
      successColor: "#3ecf8e",
      warningColor: "#e7c100",
      errorColor: "#d03050",
    },
    Button: {
      borderRadiusMedium: "9999px",
      borderRadiusSmall: "9999px",
      borderRadiusLarge: "9999px",
      fontWeight: "500",
      textColor: c.textColor1,
      textColorHover: c.textColor1,
      textColorPressed: c.textColor1,
      textColorFocus: c.textColor1,
      textColorDisabled: c.disabled,
      colorPrimary: "#3ecf8e",
      colorHoverPrimary: "#3ecf8e",
      colorPressedPrimary: "#1f4b37",
      colorFocusPrimary: "#3ecf8e",
      borderPrimary: "1px solid #3ecf8e",
      borderHoverPrimary: "1px solid #1f4b37",
      borderPressedPrimary: "1px solid #1f4b37",
      borderFocusPrimary: "1px solid #3ecf8e",
      colorInfo: "#3ecf8e",
      borderInfo: "1px solid #3ecf8e",
      colorHoverInfo: "#3ecf8e",
      borderRadius: "9999px",
    },
    Card: {
      borderRadius: "16px",
      color: c.card,
      colorEmbedded: c.embed,
      borderColor: c.border,
      titleTextColor: c.textColor1,
      titleFontWeight: "500",
      paddingMedium: "20px 24px",
    },
    Input: {
      borderRadius: "8px",
      color: c.input,
      colorFocus: c.input,
      border: "1px solid " + c.border,
      borderHover: "1px solid " + c.hover,
      borderFocus: "1px solid #3ecf8e",
      boxShadowFocus: "0 0 0 0 transparent",
      placeholderColor: c.placeholder,
      textColor: c.textColor1,
    },
    Menu: {
      borderRadius: "8px",
      color: "transparent",
      itemColorHover: c.action,
      itemColorActiveHover: c.menuActive,
      itemTextColor: c.textColor2,
      itemTextColorHover: c.textColor1,
      itemTextColorActive: "#3ecf8e",
      itemTextColorActiveHover: "#3ecf8e",
      itemIconColor: c.icon,
      itemIconColorHover: c.textColor1,
      itemIconColorActive: "#3ecf8e",
      itemIconColorActiveHover: "#3ecf8e",
      itemHeight: "36px",
      fontWeightActive: "500",
    },
    Tag: {
      borderRadius: "9999px",
      color: c.action,
      border: "1px solid " + c.border,
      textColor: c.textColor2,
    },
    Layout: {
      color: c.body,
      siderColor: c.body,
      siderBorderColor: c.border,
      headerColor: c.body,
      headerBorderColor: c.border,
    },
    Empty: {
      textColor: c.textColor3,
      iconColor: c.clear,
    },
    Spin: {
      color: "#3ecf8e",
    },
    Scrollbar: {
      color: c.scrollbar,
      colorHover: c.scrollbarHover,
    },
    Select: {
      peers: {
        InternalSelection: {
          borderRadius: "8px",
          color: c.input,
          border: "1px solid " + c.border,
          borderHover: "1px solid " + c.hover,
          borderFocus: "1px solid #3ecf8e",
          textColor: c.textColor1,
          placeholderColor: c.placeholder,
        },
      },
    },
    DataTable: {
      thColor: c.tableHeader,
      tdColor: c.table,
      borderColor: c.border,
      thTextColor: c.textColor2,
      tdTextColor: c.textColor1,
    },
  }
}
